# Generated by cucumber-sinatra. (2017-02-16 12:21:22 -0800)
require "rack/test"
require 'rspec'

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')


module TestStoreApp
  def StoreApp
    StoreApp.new
  end
end

World(TestStoreApp, Rack::Test::Methods)
