# Generated by cucumber-sinatra. (2017-02-16 12:21:22 -0800)
require "rack/test"
require 'rspec'
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app.rb')
# clean the db
ActiveRecord::Base.establish_connection
ActiveRecord::Base.connection.tables.each do |table|
  ActiveRecord::Base.connection.execute("DELETE FROM #{table}")
end

module TestStoreApp
  def app
    StoreApp.new
  end
end

World(TestStoreApp, Rack::Test::Methods)
