# Generated by cucumber-sinatra. (2017-02-14 22:11:26 +0000)
require "rack/test"
ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', '..', 'lib/app.rb')


module KnowsAboutTheStoreApp
  def StoreApp
    StoreApp.new
  end
end

World(KnowsAboutTheStoreApp, Rack::Test::Methods)
