version: '2'
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sinatra
    ports:
      - "5432:5432"
  web:
    build: .
    command: jruby -S rackup -p 3000
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
