version: '2'
services:
  db:
    image: postgres:alpine
  web:
    build: .
    command: jruby -S bundle exec jruby app.rb
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
