default: &default
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 5
  host: db
  username: postgres
  password: sinatra

development: &development
  <<: *default
  database: mystore_development

test:
  <<: *default
  database: mystore_test
