development: &development
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 5
  database: mystore_development
  host: db
  username: postgres
  password: sinatra

test: &test
  adapter: jdbcpostgresql
  encoding: unicode
  pool: 5
  database: mystore_test
  host: db
  username: postgres
  password: sinatra
